manifest:

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: mender
      url-base: https://github.com/mendersoftware

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true
    - name: mender-mcu
      remote: mender
      revision: main
      path: modules/mender-mcu

  self:
    path: mender-mcu-integration
