####################################
# W5500 Ethernet (instead of WiFi)
####################################
CONFIG_WIFI=n
CONFIG_SPI=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_ETH_W5500=y
CONFIG_ETH_W5500_TIMEOUT=1000

####################################
# LED strip stub (required by main.c)
####################################
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

####################################
# Mender storage - use existing storage_partition
####################################
CONFIG_MENDER_STORAGE_PARTITION_STORAGE_PARTITION=y

####################################
# Mender deployment logs require ISO8601 timestamps
####################################
CONFIG_LOG_OUTPUT_FORMAT_ISO8601_TIMESTAMP=y
