#!/usr/bin/env python3
"""
PNG to RGB565 C header converter.

Converts a PNG image to an RGB565 C header file suitable for embedded displays.
Supports scaling, aspect ratio preservation, and byte order configuration.
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow library required. Install with: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def rgb_to_rgb565(r: int, g: int, b: int, swap_bytes: bool = False) -> int:
    """Convert 8-bit RGB to RGB565 format."""
    # RGB565: 5 bits red, 6 bits green, 5 bits blue
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F

    rgb565 = (r5 << 11) | (g6 << 5) | b5

    if swap_bytes:
        # Swap high and low bytes for big-endian displays
        rgb565 = ((rgb565 & 0xFF) << 8) | ((rgb565 >> 8) & 0xFF)

    return rgb565


def convert_png_to_rgb565(input_path: Path, width: int, height: int, swap_bytes: bool, rotate: int = 0) -> tuple[list[int], int, int]:
    """Load PNG, scale to dimensions, and convert to RGB565."""
    img = Image.open(input_path)

    # Convert to RGB if necessary (handles RGBA, P, L, etc.)
    if img.mode != 'RGB':
        # Create white background for transparency
        if img.mode in ('RGBA', 'LA') or (img.mode == 'P' and 'transparency' in img.info):
            background = Image.new('RGB', img.size, (255, 255, 255))
            if img.mode == 'P':
                img = img.convert('RGBA')
            background.paste(img, mask=img.split()[-1] if img.mode == 'RGBA' else None)
            img = background
        else:
            img = img.convert('RGB')

    # Calculate scaling to fit within target dimensions while preserving aspect ratio
    orig_width, orig_height = img.size
    scale_w = width / orig_width
    scale_h = height / orig_height
    scale = min(scale_w, scale_h)

    new_width = int(orig_width * scale)
    new_height = int(orig_height * scale)

    # Resize with high-quality resampling
    img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)

    # Apply rotation if requested
    if rotate:
        img = img.rotate(rotate, expand=False)

    # Convert pixels to RGB565
    pixels = []
    for y in range(new_height):
        for x in range(new_width):
            r, g, b = img.getpixel((x, y))
            pixels.append(rgb_to_rgb565(r, g, b, swap_bytes))

    return pixels, new_width, new_height


def generate_header(pixels: list[int], width: int, height: int, swap_bytes: bool) -> str:
    """Generate C header file content."""
    byte_order = "big-endian (byte-swapped)" if swap_bytes else "little-endian"

    lines = [
        "/*",
        f" * Mender logo - RGB565 format ({byte_order})",
        f" * Size: {width}x{height}",
        " * Auto-generated by png_to_rgb565.py - do not edit",
        " */",
        "",
        "#ifndef MENDER_LOGO_H",
        "#define MENDER_LOGO_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define MENDER_LOGO_WIDTH  {width}",
        f"#define MENDER_LOGO_HEIGHT {height}",
        "",
        f"static const uint16_t mender_logo_rgb565[{len(pixels)}] = {{",
    ]

    # Format pixel data in rows of 16 values
    for i in range(0, len(pixels), 16):
        row = pixels[i:i+16]
        row_str = ",".join(f"0x{p:04x}" for p in row)
        if i + 16 < len(pixels):
            row_str += ","
        lines.append(f"    {row_str}")

    lines.extend([
        "};",
        "",
        "#endif /* MENDER_LOGO_H */",
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG to RGB565 C header for embedded displays"
    )
    parser.add_argument(
        "--input", "-i",
        type=Path,
        required=True,
        help="Input PNG file"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=None,
        help="Output header file (default: stdout)"
    )
    parser.add_argument(
        "--width", "-W",
        type=int,
        default=280,
        help="Maximum width (default: 280)"
    )
    parser.add_argument(
        "--height", "-H",
        type=int,
        default=94,
        help="Maximum height (default: 94)"
    )
    parser.add_argument(
        "--swap-bytes",
        action="store_true",
        help="Swap bytes for big-endian displays (e.g., ILI9341)"
    )
    parser.add_argument(
        "--rotate",
        type=int,
        default=0,
        choices=[0, 90, 180, 270],
        help="Rotate image by degrees (default: 0)"
    )

    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    pixels, width, height = convert_png_to_rgb565(
        args.input, args.width, args.height, args.swap_bytes, args.rotate
    )

    header = generate_header(pixels, width, height, args.swap_bytes)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(header)
        print(f"Generated {args.output} ({width}x{height}, {len(pixels)} pixels)", file=sys.stderr)
    else:
        print(header)


if __name__ == "__main__":
    main()
